name: Verify Extensions Data

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd scripts
          npm ci

      - name: Sync Extensions Data
        run: |
          cd scripts
          node index.js
